---
# Role configure tasks

- name: Configure main file
  ansible.builtin.template:
    src: main.cf.j2
    dest: "{{ postfix_config_dir }}/main.cf"
    lstrip_blocks: "yes"
    trim_blocks: "yes"
    owner: "{{ postfix_user }}"
    group: "{{ postfix_group }}"
    mode: "{{ postfix_mode }}"
  vars:
    _postfix_main_params: >-
       {{ lookup('template', 'main_params.j2') | from_yaml }}
  notify:
    - reload main config

- name: Configure lookup tables
  ansible.builtin.template:
    src: file.j2
    dest: "{{ postfix_config_dir }}/{{ postfix_file.filename }}"
    lstrip_blocks: "yes"
    trim_blocks: "yes"
    owner: "{{ postfix_user }}"
    group: "{{ postfix_group }}"
    mode: "{{ postfix_mode }}"
  loop: "{{ postfix_files | list }}"
  loop_control:
    loop_var: postfix_file
    label: "{{ postfix_file.filename }}"
  when:
    - postfix_file.filename is defined
    - postfix_file.filename | bool
    - postfix_file.state is defined
    - postfix_file.state == 'present'
  register: configure_lookup_tables_result
  notify:
    - reload lookup tables

- name: Remove lookup tables
  file:
    path: "{{ postfix_config_dir }}/{{ postfix_file.filename }}"
    state: absent
  loop: "{{ postfix_files | list }}"
  loop_control:
    loop_var: postfix_file
    label: "{{ postfix_file.filename }}"
  when:
    - postfix_file.filename is defined
    - postfix_file.filename | bool
    - postfix_file.state is defined
    - postfix_file.state == 'absent'
  register: remove_lookup_tables_result
  notify:
    - reload lookup tables

- name: Create/rebuild local databases
  command: >-
      postmap {{ local_database.type ~ ':' 
                 ~ postfix_config_dir ~ '/' 
                 ~ local_database.filename 
              }}
  loop: "{{ _postfix_local_databases }}"
  loop_control:
    loop_var: local_database
    label: "{{ local_database.type ~ ':' ~ local_database.filename }}"
  changed_when: no
  vars:
    _postfix_local_databases: >-
      {{ configure_lookup_tables_result.results
         | json_query('[? changed==`true` 
                       && postfix_file.state==`present`].{
                            filename: postfix_file.filename, 
                            type: postfix_file.lookup_type}') }}

- name: Remove local databases
  file:
    path: "{{ postfix_config_dir }}/{{ local_database }}"
    state: absent
  loop: "{{ _postfix_local_databases }}"
  loop_control:
    loop_var: local_database
    label: "{{ local_database }}"
  vars:
    _postfix_local_databases: >-
      {{ remove_lookup_tables_result.results
         | select('changed')
         | selectattr("postfix_file.lookup_type", "defined")
         | selectattr('postfix_file.lookup_type', 
                      'in', postfix_local_database_types)
         | map(attribute='postfix_file.filename')
         | map("regex_replace", "^(.*)$", "\1.db")
         | list }}

- name: Validate configuration
  command: postfix check
  register: postfix_check_result
  changed_when: no
  failed_when:  postfix_check_result.rc != 0
