---
# Role install tasks

- name: Install postfix packages
  package:
    name: "{{ postfix_package }}"
    state: present
  loop: "{{ postfix_packages }}"
  loop_control:
    loop_var: postfix_package
    label: postfix_package
