---

- name: Configure postfix daemon
  include_tasks: configure.yml
  tags:
    - role::postfix
    - role::postfix::configure

- name: Setup postfix daemon service
  include_tasks: service.yml
  tags:
    - role::postfix
    - role::postfix::service
