---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: podman
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:centos7
    dockerfile: Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:stream8
    dockerfile: Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: "fedora34-${INSTANCE_UUID:-1}"
    image: quay.io/fedora/fedora:34
    dockerfile: Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_34
  - name: "fedora35-${INSTANCE_UUID:-1}"
    image: quay.io/fedora/fedora:35
    dockerfile: Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_35
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          postfix_config_dir: /etc/postfix
          test_user: user001
          test_password: pass001
          test_user_from: foobar
          postfix_main_params:
            mydomain: example.com
            inet_protocols: ipv4
            mydestination:
              - $$myhostname
              - $$mydomain
              - localhost.$$mydomain
              - localhost
            relayhost: [mail.example.com]
            relay_domains:
            mynetworks:
              - 127.0.0.0/8
            smtpd_sasl_path: smtpd
            smtpd_sasl_auth_enable: "yes"
            smtpd_tls_auth_only: "no"
            smtpd_recipient_restrictions:
              - permit_mynetworks
              - reject
            transport_maps:
              - hash:/etc/postfix/transport_test
            home_mailbox: Maildir/
          postfix_files:
            - file: /etc/sasl2/smtpd.conf
              description: Auth backend
              state: present
              content: |-
                pwcheck_method: saslauthd
                mech_list: PLAIN LOGIN
            - file: "{{ postfix_config_dir }}/transport_test"
              description: Transport rules
              state: present
              lookup_type: hash
              content: |-
                example.com     local:
                *               discard:
            - file: "{{ postfix_config_dir }}/bogus_data"
              state: absent
              lookup_type: hash
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
