---

- name: Prepare
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Setup required packages for tests
      ansible.builtin.package:
        state: present
        name: "{{ pkg_test }}"
      loop:
        - cyrus-sasl
        - cyrus-sasl-plain
      loop_control:
        loop_var: pkg_test
        label: "{{ pkg_test }}"

    - name: Start saslauthd
      ansible.builtin.systemd:
        name: saslauthd
        enabled: yes
        state: started

    - name: Create test group
      ansible.builtin.group:
        name: users
        state: present

    - name: Create test user
      ansible.builtin.user:
        name: "{{ test_user }}"
        password: "{{ test_password | password_hash('sha512') }}"
        create_home: yes
        state: present
        group: users

    - name: Create postfix directory
      ansible.builtin.file:
        path: "{{ postfix_config_dir }}"
        state: directory
        mode: "0755"

    - name: Create bogus data files
      ansible.builtin.file:
        path: "{{ postfix_config_dir }}/{{ item }}"
        state: touch
        mode: "0644"
      loop:
        - bogus_data
        - bogus_data.db
