---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Check if deleted files still exist
      ansible.builtin.find:
        paths: "{{ postfix_config_dir }}"
        patterns: bogus*
      register: find_result
      changed_when: no
      failed_when: find_result.matched != 0

    - name: Check for valid postfix banner
      ansible.builtin.wait_for:
        host: 127.0.0.1
        delay: 1
        port: 25
        search_regex: "^220 "
        timeout: 5
      register: check_smtp_banner_result

    - name: Get timestamp  # noqa jinja[spacing]
      ansible.builtin.set_fact:
        timestamp: "{{ lookup('pipe','date +%s') }}"

    - name: Send basic mail
      mail:
        host: 127.0.0.1
        port: 25
        from: "{{ test_user_from }}@{{ postfix_main_params.mydomain }}"
        to: "{{ test_user }}@{{ postfix_main_params.mydomain }}"
        subject: "Basic mail {{ timestamp }}"

    - name: Check basic mail
      ansible.builtin.command: journalctl --no-pager -u postfix
      register:  journalctl_result
      changed_when: no
      failed_when: >-
        not journalctl_result.stdout
            is search("postfix/local.*to=<"
                      ~ test_user
                      ~ "@"
                      ~ postfix_main_params.mydomain
                      ~ ">.*status=sent.*" )

    - name: Pause for 1 second
      ansible.builtin.pause:
        seconds: 1

    - name: Cleanup journal
      ansible.builtin.command: journalctl --vacuum-time=1seconds
      changed_when: no

    - name: Send autheticated mail
      mail:
        host: 127.0.0.1
        port: 25
        from: "{{ test_user_from }}@{{ postfix_main_params.mydomain }}"
        to: "{{ test_user }}@{{ postfix_main_params.mydomain }}"
        subject: "Authenticated mail {{ timestamp }}"
        username: "{{ test_user }}"
        password: "{{ test_password }}"

    - name: Check autheticated mail
      ansible.builtin.command: journalctl --no-pager -u postfix
      register:  journalctl_result
      changed_when: no
      failed_when: >-
        not journalctl_result.stdout
            is search("postfix/local.*to=<"
                      ~ test_user
                      ~ "@"
                      ~ postfix_main_params.mydomain
                      ~ ">.*status=sent.*" )

    - name: Pause for 1 second
      ansible.builtin.pause:
        seconds: 1

    - name: Cleanup journal
      ansible.builtin.command: journalctl --vacuum-time=1seconds
      changed_when: no

    - name: Get timestamp  # noqa jinja[spacing]
      ansible.builtin.set_fact:
        timestamp: "{{ lookup('pipe','date +%s') }}"

    - name: Send external mail with transport rules
      mail:
        host: 127.0.0.1
        port: 25
        from: "{{ test_user_from }}@{{ postfix_main_params.mydomain }}"
        to: "user-{{ timestamp }}@example.external"
        subject: "Basic mail {{ timestamp }}"

    - name: Check external mail with transport rules
      ansible.builtin.command: journalctl --no-pager -u postfix -n 6
      register:  journalctl_result
      changed_when: no
      failed_when: >-
        not journalctl_result.stdout | regex_search("discard.*user-"
                                       ~ timestamp ~ "@.*dsn=2\.")
